name: SHASUM summary

on:
  pull_request:
    branches: [ "main" ]

jobs:
  comment-summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show changed files
        run: |
          git diff --no-commit-id --name-only ${{ github.event.pull_request.base.sha }}..HEAD
      - name: run shasum-summary
        run: python3 contrib/shasum-summary/main.py ${{ github.event.pull_request.base.sha }}..HEAD > comment
      - name: show comment
        run: cat comment
      - name: Store issue number
        run: echo "${{ github.event.number }}" > issue-number
      - name: Verify issue number file
        run: cat issue-number
      - uses: actions/upload-artifact@v4
        with:
          name: shasum-comment
          path: |
            comment
            issue-number
